export default function handler(req: any, res: any) {
  const data = {
    "forms": [
      {
        "id": "Q-001",
        "name": "New Patient Intake",
        "type": "Questionnaire",
        "category": "Registration",
        "status": "active",
        "version": "2.1",
        "description": "Comprehensive intake form for new patients",
        "estimatedTime": "15-20 minutes",
        "sections": 5,
        "questions": 28,
        "languages": ["English", "Spanish"],
        "requiredFor": ["First Visit", "New Patient"],
        "lastUpdated": "November 15, 2025",
        "createdBy": "Dr. Sarah Chen"
      },
      {
        "id": "Q-002",
        "name": "Financial Consent",
        "type": "Consent",
        "category": "Financial",
        "status": "active",
        "version": "1.5",
        "description": "Financial responsibility and payment terms agreement",
        "estimatedTime": "5 minutes",
        "sections": 3,
        "questions": 8,
        "languages": ["English", "Spanish", "Chinese"],
        "requiredFor": ["All Visits", "Registration"],
        "lastUpdated": "October 22, 2025",
        "createdBy": "Admin Team"
      },
      {
        "id": "Q-003",
        "name": "HIPAA Privacy Consent",
        "type": "Consent",
        "category": "Legal",
        "status": "active",
        "version": "3.0",
        "description": "HIPAA privacy practices acknowledgment",
        "estimatedTime": "3 minutes",
        "sections": 2,
        "questions": 4,
        "languages": ["English", "Spanish"],
        "requiredFor": ["All Visits", "Registration"],
        "lastUpdated": "November 1, 2025",
        "createdBy": "Legal Department"
      },
      {
        "id": "Q-004",
        "name": "COVID-19 Screening",
        "type": "Screening",
        "category": "Clinical",
        "status": "active",
        "version": "1.8",
        "description": "Pre-visit COVID-19 symptom screening",
        "estimatedTime": "2 minutes",
        "sections": 1,
        "questions": 6,
        "languages": ["English", "Spanish"],
        "requiredFor": ["In-Person Visits"],
        "lastUpdated": "September 10, 2025",
        "createdBy": "Clinical Team"
      },
      {
        "id": "Q-005",
        "name": "Medication History",
        "type": "Questionnaire",
        "category": "Clinical",
        "status": "active",
        "version": "2.0",
        "description": "Current medications, allergies, and pharmacy information",
        "estimatedTime": "10 minutes",
        "sections": 3,
        "questions": 15,
        "languages": ["English", "Spanish"],
        "requiredFor": ["First Visit", "Annual Review"],
        "lastUpdated": "November 10, 2025",
        "createdBy": "Dr. Michael Torres"
      },
      {
        "id": "Q-006",
        "name": "Mental Health Assessment (PHQ-9)",
        "type": "Assessment",
        "category": "Mental Health",
        "status": "active",
        "version": "1.0",
        "description": "Patient Health Questionnaire for depression screening",
        "estimatedTime": "5 minutes",
        "sections": 1,
        "questions": 9,
        "languages": ["English", "Spanish"],
        "requiredFor": ["Mental Health Visits"],
        "lastUpdated": "August 15, 2025",
        "createdBy": "Dr. Lisa Wong"
      },
      {
        "id": "Q-007",
        "name": "Surgical Consent",
        "type": "Consent",
        "category": "Surgical",
        "status": "active",
        "version": "4.2",
        "description": "Pre-operative consent and risk acknowledgment",
        "estimatedTime": "10 minutes",
        "sections": 4,
        "questions": 12,
        "languages": ["English", "Spanish"],
        "requiredFor": ["Surgical Procedures"],
        "lastUpdated": "November 18, 2025",
        "createdBy": "Surgical Department"
      },
      {
        "id": "Q-008",
        "name": "Post-Visit Satisfaction Survey",
        "type": "Survey",
        "category": "Quality",
        "status": "active",
        "version": "1.3",
        "description": "Patient experience and satisfaction feedback",
        "estimatedTime": "3 minutes",
        "sections": 2,
        "questions": 10,
        "languages": ["English", "Spanish"],
        "requiredFor": ["Post-Visit"],
        "lastUpdated": "October 5, 2025",
        "createdBy": "Quality Team"
      }
    ],
    "categories": [
      "Registration",
      "Financial",
      "Legal",
      "Clinical",
      "Mental Health",
      "Surgical",
      "Quality"
    ],
    "types": [
      "Questionnaire",
      "Consent",
      "Screening",
      "Assessment",
      "Survey"
    ]
  };

  res.status(200).json(data);
}
